name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Sonarcube scan
      uses: jinguji/sonarcloud-gradle-github-action@v2
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
        sonar-organization: default-organization
        sonar-project-key: KotlinMailSystem
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
